%ANA GABRIELA GOMEZ HERNANDEZ
%Programa: El Yerberito Ilustrado
%Pasos de 1 al 5 de la asignacion
%Conocimiento
hierba_para(diente_leon,acido_urico).
hierba_para(mazanilla,digestion).
hierba_para(abrojo,afeccio_pecho).
hierba_para(abrojo,inflamacion_ojos).
hierba_para(abrojo,inflamacion_higado).
hierba_para(abrojo,circulacion_sangre).
hierba_para(acacia,garganta_estropeada).
hierba_para(acacia,tos).
hierba_para(acacia,bronquitis).
hierba_para(acanto,picadura_araña).
hierba_para(acanto,sacar_veneno).
hierba_para(acanto,desinflamar_picadura).
hierba_para(acanto,almorranas).
hierba_para(acanto,ardor_orina).
hierba_para(acanto,heridas_golpe).
hierba_para(acanto,heridas_caida).
hierba_para(acanto,dispepsia).
hierba_para(acanto,disenteria).
hierba_para(aceitilla,cansancio_intelectual).
hierba_para(aceitilla,depresion_nerviosa).
hierba_para(aceitilla,cansancio).
hierba_para(achicoria,indigestion).
hierba_para(achicoria,colicos_biliosos).
hierba_para(achicoria,bilis).
hierba_para(achicoria,purificar_riñones).
hierba_para(achicoria,purificar_riñones).
hierba_para(malva,abcesos).
hierba_para(zarzaparrila,abceso_hepatico).
hierba_para(anis,acidez_estomacal).
hierba_para(perejil,acidez_estomacal).
hierba_para(sanguinaria,acido_urico).
hierba_para(limon,acido_urico).
hierba_para(sauco,acido_urico).
hierba_para(arnica,acne).
hierba_para(llanten,aftas).
hierba_para(fenogreco,aftas).
hierba_para(zarzamora,aftas).
hierba_para(salvia,agotamiento).
hierba_para(tilo,agotamiento).
hierba_para(valeriana,agotamiento).
hierba_para(yerbabuena,agruras).
hierba_para(manzanilla,agruras).
hierba_para(jugo_limon,agruras).
hierba_para(jugo_toronja,agruras).
hierba_para(pingüica,albuminaria).
hierba_para(quina_roja,albuminaria).
hierba_para(encino_rojo,albuminaria).
hierba_para(pimiento,alcholismo).
hierba_para(salvia,almorranas).
hierba_para(hamamelis,almorranas).
hierba_para(sanguinaria,almorranas).
hierba_para(cola_caballo,almorranas).
hierba_para(arnica,almorranas).
hierba_para(toques,almorranas).
hierba_para(sauco,almorranas).
hierba_para(ajenjo,anemia).
hierba_para(germen_trigo,anemia).
hierba_para(quina,anemia).
hierba_para(canela,anemia).
hierba_para(halholva,anemia).
hierba_para(eucalipto,anginas).
hierba_para(cebada,anginas).
hierba_para(salvia,anginas).
hierba_para(tabachin,anginas).
hierba_para(borroja,anginas).
hierba_para(ajenjo,anorexia).
hierba_para(gerciana,anorexia).
hierba_para(yerbabuena,anorexia).
hierba_para(limon,arterosclerosis).
hierba_para(gerciana,arterosclerosis).
hierba_para(cardo,arterosclerosis).
hierba_para(zarzaparrilla,arterosclerosis).
hierba_para(arnica,arterosclerosis).
hierba_para(chicalote,arterosclerosis).
hierba_para(alcanfor,arterosclerosis).
hierba_para(toronja,arterosclerosis).
hierba_para(limon,artritis).
hierba_para(gerciana,artritis).
hierba_para(cardo,artritis).
hierba_para(zarzaparrilla,artritis).
hierba_para(arnica,artritis).
hierba_para(chicalote,artritis).
hierba_para(alcanfor,artritis).
hierba_para(toronja,artritis).
hierba_para(eucalipto,asma).
hierba_para(marrubio,asma).
hierba_para(toloache,asma).
hierba_para(oregano,asma).
hierba_para(salvia,asma).
hierba_para(lupulo,atonia_estomacal).
hierba_para(eucalipto,atonia_estomacal).
hierba_para(cuasia,atonia_estomacal).
hierba_para(uva,bazo).
hierba_para(cerezo,bazo).
hierba_para(malva,boca_inflamacion).
hierba_para(rosal,boca_inflamacion).
hierba_para(limon,boca_inflamacion).
hierba_para(salvia,boca_inflamacion).
hierba_para(malva,estomatitis).
hierba_para(rosal,estomatitis).
hierba_para(limon,estomatitis).
hierba_para(salvia,estomatitis).
hierba_para(eucalipto,bronquitis).
hierba_para(borraja,bronquitis).
hierba_para(anacahuite,bronquitis).
hierba_para(gordolobo,bronquitis).
hierba_para(tilo,bronquitis).
hierba_para(benjui,bronquitis).
hierba_para(marrubio,bronquitis).
hierba_para(rabano,bronquitis).
hierba_para(cordolobo,bronconeumonia).
hierba_para(eucalipto,bronconeumonia).
hierba_para(ipecacuana,bronconeumonia).
hierba_para(mostaza,bronconeumonia).
hierba_para(ortiga,caida_cabello).
hierba_para(espinosilla,caida_cabello).
hierba_para(marrubio,caida_cabello).
hierba_para(romero,caida_cabello).
hierba_para(anis,calambres).
hierba_para(tila,calambres).
hierba_para(manzanilla,calambres).
hierba_para(ajenjo,calambres).
hierba_para(diente_leon,calculos_bilares).
hierba_para(aceite_oliva,calculos_bilares).
hierba_para(retoma,calculos_bilares).
hierba_para(cabellos_elote,calculos_renales).
hierba_para(pingüice,calculos_renales).
hierba_para(cola_caballo,calculos_renales).
hierba_para(ajo,callos).
hierba_para(cebolla,callos).
hierba_para(hiedra,caries).
hierba_para(cola_caballo,caries).
hierba_para(ortiga,caspa).
hierba_para(limon,caspa).
hierba_para(romero,caspa).
hierba_para(chuachalalate,cancer_utero).
hierba_para(llanten,cancer_utero).
hierba_para(siempreviva,cancer_utero).
hierba_para(mastuerzo,ciatica).
hierba_para(higuera,ciatica).
hierba_para(sauco,ciatica).
hierba_para(toronjil,circulacion).
hierba_para(sanguinaria,circulacion).
hierba_para(salvia,circulacion).
hierba_para(hamamelis,circulacion).
hierba_para(cola_caballo,cistitis).
hierba_para(doradilla,cistitis).
hierba_para(ajo,cistitis).
hierba_para(cabellos_elote,cistitis).
hierba_para(menta,colicos).
hierba_para(hinojo,colicos).
hierba_para(manzanilla,colicos).
hierba_para(toronjil,colicos).
hierba_para(boido,colicos).
hierba_para(linoza,colitis).
hierba_para(anis,colitis).
hierba_para(romero,colitis).
hierba_para(cola_caballo,colitis).
hierba_para(cabellos_elote,colitis).
hierba_para(arnica,contusiones).
hierba_para(hamamelis,contusiones).
hierba_para(laurel,contusiones).
hierba_para(brionia,contusiones).
hierba_para(digital,corazon_tomico).
hierba_para(salvia,corazon_tomico).
hierba_para(nuez_kcla,corazon_tomico).
hierba_para(tejocote,corazon_tomico).
hierba_para(uchicoria,depurativos_sangre).
hierba_para(diente_leon,depurativos_sangre).
hierba_para(apio,depurativos_sangre).
hierba_para(sanguinara,depurativos_sangre).
hierba_para(zarzaparrilla,depurativos_sangre).
hierba_para(berro,depurativos_sangre).
hierba_para(matarique,diabetes).
hierba_para(tronadora,diabetes).
hierba_para(eucalipto,diabetes).
hierba_para(damiana,diabetes).
hierba_para(capulin,diarrea_cronica).
hierba_para(mezquite_corteza,diarrea_cronica).
hierba_para(tlachichinole,diarrea_cronica).
hierba_para(linaza,diarrea_irritacion).
hierba_para(membtrillo,diarrea_irritacion).
hierba_para(arroz,diarrea_irritacion).
hierba_para(cebada,diarrea_irritacion).
hierba_para(guayaba,diarrea_inflamacion).
hierba_para(albahaca,diarrea_inflamacion).
hierba_para(granada,diarrea_inflamacion).
hierba_para(manzanilla,diarrea_verdosa).
hierba_para(simonillo,diarrea_verdosa).
hierba_para(sirmpretiva,diarrea_verdosa).
hierba_para(chaparro_amargoso,diarrea_sangre).
hierba_para(muicle,diarrea_sangre).
hierba_para(monacillo,diarrea_sangre).
hierba_para(limon,difteria).
hierba_para(naranja,difteria).
hierba_para(tamarindo,disenteria).
hierba_para(chaparro_amargoso,disenteria).
hierba_para(ipecacuiame,disenteria).
hierba_para(cedral,disenteria).
hierba_para(amis,dispepsia_hiperc).
hierba_para(menta,dispepsia_hiperc).
hierba_para(yerbabuena,dispepsia_hiperc).
hierba_para(diente_leon,dispepsia_hiperc).
hierba_para(quina,dispepsia_hipoc).
hierba_para(genciana,dispepsia_hipoc).
hierba_para(tabaquillo,dispepsia_hipoc).
hierba_para(ruibardo,dispepsia_hipoc).
hierba_para(anis_estrella,dolor).
hierba_para(valeriana,dolor).
hierba_para(manzanilla,dolor).
hierba_para(alcanfor,dolor_musculares).
hierba_para(tamarindo,empacho).
hierba_para(linaza,enteritis).
hierba_para(cedron,enteritis).
hierba_para(llanten,enteritis).
hierba_para(valeriana,epilepsia).
hierba_para(hierba_pollo,epistaxis).
hierba_para(cebolla,epistaxis).
hierba_para(perejil,epistaxis).
hierba_para(sauco,erisipela).
hierba_para(hiedra,erisipela).
hierba_para(zanahoria,erisipela).
hierba_para(borraja,escarlatina).
hierba_para(sauco,escarlatina).
hierba_para(cebolla,escarlatina).
hierba_para(ajo,escorbuto).
hierba_para(limon,escorbuto).
hierba_para(berro,escorbuto).
hierba_para(cebolla,escorbuto).
hierba_para(gexanio,escorbuto).
hierba_para(ciruela,estreñimiento).
hierba_para(linaza,estreñimiento).
hierba_para(chia,estreñimiento).
hierba_para(tamarindo,estreñimiento).
hierba_para(agar,estreñimiento).
hierba_para(eucalipto,faringitis).
hierba_para(larenda,faringitis).
hierba_para(anacahuite,faringitis).
hierba_para(apio,flatulencias).
hierba_para(tomillo,flatulencias).
hierba_para(perejil,flatulencias).
hierba_para(amis_estrella,flatulencias).
hierba_para(hinojo,flatulencias).
hierba_para(toronjill,flatulencias).
hierba_para(romero,flatulencias).
hierba_para(ruibardo,flatulencias).
hierba_para(ruida,flatulencias).
hierba_para(menta,flatulencias).
hierba_para(arnica,flebitis).
hierba_para(alfalfa,flebitis).
hierba_para(lino,flebitis).
hierba_para(malvavisco,flebitis).
hierba_para(romero,flebitis).
hierba_para(quina,flebitis).
hierba_para(genciana,flemas).
hierba_para(oregano,flemas).
hierba_para(fenogreco,forunculos).
hierba_para(malvavisco,forunculos).
hierba_para(hiedra,forunculos).
hierba_para(manzanilla,gastralgia).
hierba_para(amis_estrella,gastralgia).
hierba_para(cola_caballo,gonorrea).
hierba_para(doradilla,gonorrea).
hierba_para(zarzaparrilla,gonorrea).
hierba_para(apio,gota).
hierba_para(cerezo,gota).
hierba_para(limon,gota).
hierba_para(pino,gota).
hierba_para(alcanfor,gota).
hierba_para(aconito,gota).
hierba_para(belladora,gota).
hierba_para(beleño,gota).
hierba_para(colchito,gota).
hierba_para(chicalote,gota).
hierba_para(encina,grietas_ano).
hierba_para(encina,grietas_pezon).
hierba_para(nogal,grietas_pezon).
hierba_para(milenrana,grietas_pezon).
hierba_para(eucalipto,gripa).
hierba_para(limon,gripa).
hierba_para(quina,gripa).
hierba_para(zarzaparrilla,gripa).
hierba_para(calendula,gripa).
hierba_para(menta,halitosis).
hierba_para(hinojo,halitosis).
hierba_para(mastuerzo,hemorragia_interna).
hierba_para(ortiga,hemorragia_interna).
hierba_para(rosal,hemorragia_interna).
hierba_para(retama,hepatitis).
hierba_para(boldo,hepatitis).
hierba_para(alcachofa,hepatitis).
hierba_para(prodigiosa,hepatitis).
hierba_para(cascara_sagrada,hepatitis).
hierba_para(helecho,hernia).
hierba_para(ricino,hernia).
hierba_para(tabaco,hernia).
hierba_para(linaza,herpes).
hierba_para(llanten,herpes).
hierba_para(arnica,heridas).
hierba_para(hamamelis,heridas).
hierba_para(alcachofa,hidropesia).
hierba_para(cardo,hidropesia).
hierba_para(perejil,hidropesia).
hierba_para(sauco,hidropesia).
hierba_para(benos,hidropesia).
hierba_para(retama,hidropesia).
hierba_para(marubio,higado_congestion).
hierba_para(boldo,higado_congestion).
hierba_para(doradilla,higado_congestion).
hierba_para(ruibarbo,higado_congestion).
hierba_para(manzanilla,higado_colicos).
hierba_para(lechuga,higado_bilis).
hierba_para(tila,higado_bilis).
hierba_para(papoloquelite,higado_letexicia).
hierba_para(achicoria,higado_letexicia).
hierba_para(berros,higado_letexicia).
hierba_para(llanton,higado_letexicia).
hierba_para(retoma,higado_letexicia).
hierba_para(tecomasuchil,higado_letexicia).
hierba_para(ajo,hipertension_alta).
hierba_para(esparrago,hipertension_alta).
hierba_para(alpiste,hipertension_alta).
hierba_para(muerdago,hipertension_alta).
hierba_para(miel,hipertension_baja).
hierba_para(nuez_kola,hipertension_baja).
hierba_para(crategus,hipertension_baja).
hierba_para(acadera,hipertension_baja).
hierba_para(amis,hipo).
hierba_para(hinojo,hipo).
hierba_para(tila,hipo).
hierba_para(valeriana,hipo).
hierba_para(azahar,histerismo).
hierba_para(beleño,histerismo).
hierba_para(gelsenio,histerismo).
hierba_para(tita,histerismo).
hierba_para(valeriana,histerismo).
hierba_para(pasiflora,insomio).
hierba_para(azahar,insomio).
hierba_para(menta,insomio).
hierba_para(manzanilla,insomio).
hierba_para(lechuga,insomio).
hierba_para(tila,insomio).
hierba_para(genciana,intestino).
hierba_para(melisa,intestino).
hierba_para(yohimbo,impotencia_sexual).
hierba_para(domiana,impotencia_sexual).
hierba_para(nuez_vomica,impotencia_sexual).
hierba_para(aguacate,impotencia_sexual).
hierba_para(manzanilla,jaqueca).
hierba_para(acomito,jaqueca).
hierba_para(valeriana,jaqueca).
hierba_para(tila,jaqueca).
hierba_para(chicalote,jaqueca).
hierba_para(hinojo,lactancia).
hierba_para(anis,lactancia).
hierba_para(menta,lactancia).
hierba_para(perejil,lactancia).
hierba_para(zanahoria,lactancia).
hierba_para(aconito,laringitis).
hierba_para(borraja,laringitis).
hierba_para(cebolla,laringitis).
hierba_para(rosa,laringitis).
hierba_para(benjui,laringitis).
hierba_para(encino,laringitis).
hierba_para(encina,leucorrea).
hierba_para(zarzaparilla,leucorrea).
hierba_para(pino,leucorrea).
hierba_para(enebro,leucorrea).
hierba_para(gerciana,leucorrea).
hierba_para(ajenjo,lombrices).
hierba_para(ajo,lombrices).
hierba_para(cebolla,lombrices).
hierba_para(betonia,lombrices).
hierba_para(aguacate,lombrices).
hierba_para(papaya,lombrices).
hierba_para(epazote,lombrices).
hierba_para(avena,lumbago).
hierba_para(cebada,lumbago).
hierba_para(tomillo,lumbago).
hierba_para(verbena,lumbago).
hierba_para(fenogreco,llagas).
hierba_para(eucalipto,llagas).
hierba_para(llanten,llagas).
hierba_para(sanguinaria,llagas).
hierba_para(quina,malaria).
hierba_para(girasol,malaria).
hierba_para(eucalipto,malaria).
hierba_para(cardo,malaria).
hierba_para(azahar,menopausia).
hierba_para(hamamelis,menopausia).
hierba_para(tila,menopausia).
hierba_para(quina_roja,menopausia).
hierba_para(azfran,menstruacion_abundante).
hierba_para(hamamelis,menstruacion_abundante).
hierba_para(belladona,menstruacion_dolorosa).
hierba_para(anis_estrella,menstruacion_dolorosa).
hierba_para(ruda,menstruacion_esacasa).
hierba_para(ajenjo,menstruacion_escasa).
hierba_para(manzanilla,menstruacion_escasa).
hierba_para(apio,menstruacion_irregular).
hierba_para(hisopo,menstruacion_irregular).
hierba_para(quina_amarilla,menstruacion_irregular).
hierba_para(sabina,menstruacion_irregular).
hierba_para(artemisa,menstruacion_irregular).
hierba_para(hamamelis,metorragia).
hierba_para(zapatle,metorragia).
hierba_para(perejil,metorragia).
hierba_para(cuerecillo_centeno,metorragia).
hierba_para(clavo,dolor_muelas).
hierba_para(hiedra,dolor_muelas).
hierba_para(ortiga,hemorragia_nasal).
hierba_para(cola_caballo,hemorragia_nasal).
hierba_para(ruda,hemorragia_nasal).
hierba_para(eucalipto,hemorragia_nasal).
hierba_para(anis,nauseas).
hierba_para(ajenjo,nauseas).
hierba_para(menta,nauseas).
hierba_para(salvio,nauseas).
hierba_para(manzanillo,neuralgias).
hierba_para(menta,neuralgias).
hierba_para(valeriana,neuralgias).
hierba_para(boldo,neuralgias).
hierba_para(pasiflora,neurastenia).
hierba_para(te_negro,neurastenia).
hierba_para(mate,neurastenia).
hierba_para(valeriana,neurastenia).
hierba_para(linaza,nefritis).
hierba_para(grame,nefritis).
hierba_para(cebada,nefritis).
hierba_para(llanten,nefritis).
hierba_para(doradilla,nefritis).
hierba_para(esparrago,nefritis).
hierba_para(ruda,nefritis).
hierba_para(torongil,obesidad).
hierba_para(marrubio,obesidad).
hierba_para(limon,obesidad).
hierba_para(malva,obesidad).
hierba_para(esparrago,obesidad).
hierba_para(boldo,oido).
hierba_para(aceite_oliva,oido).
hierba_para(llanten,oido).
hierba_para(hiedra,oido).
hierba_para(manzanilla,conjuntiritis_irritacion_ojos).
hierba_para(limon,conjuntiritis_irritacion_ojos).
hierba_para(llanten,conjuntiritis_irritacion_ojos).
hierba_para(salvia,conjuntiritis_irritacion_ojos).
hierba_para(ruda,conjuntiritis_irritacion_ojos).
hierba_para(rosal,conjuntiritis_irritacion_ojos).
hierba_para(ajenjo,paludismo).
hierba_para(quina,paludismo).
hierba_para(berro,pecas).
hierba_para(genciana,pecas).
hierba_para(rabano,pecas).
hierba_para(papaya,pecas).
hierba_para(laurel,pies_oloroso).
hierba_para(encina,pies_oloroso).
hierba_para(miel,piquete_abeja).
hierba_para(perejil,piquete_abeja).
hierba_para(cebolla,piquete_abeja).
hierba_para(puerro,piquete_abeja).
hierba_para(fresno,piquete_araña).
hierba_para(ipecacuana,piquete_araña).
hierba_para(alcanfor,piquete_mosco).
hierba_para(perejil,piquete_mosco).
hierba_para(hamamelis,piquete_mosco).
hierba_para(anagolida,piquete_vibora).
hierba_para(jengibre,pleuresia).
hierba_para(linaza,pleuresia).
hierba_para(cardo,pleuresia).
hierba_para(girasol,pleuresia).
hierba_para(ipecacuama,piorrea).
hierba_para(rosal,prostata).
hierba_para(eucalipto,pulmonia).
hierba_para(ocote,pulmonia).
hierba_para(gordolobo,pulmonia).
hierba_para(borraja,pulmonia).
hierba_para(sauco,pulmonia).
hierba_para(linaza,quemaduras).
hierba_para(cebolla,quemaduras).
hierba_para(hiedra,quemaduras).
hierba_para(gordolobo,quemaduras).
hierba_para(nogal,raquitismo).
hierba_para(ajo,reumatismo).
hierba_para(apio,reumatismo).
hierba_para(borraja,reumatismo).
hierba_para(gobernadora,reumatismo).
hierba_para(pino,reumatismo).
hierba_para(romero,reumatismo).
hierba_para(sanguinaria,reumatismo).
hierba_para(marrubio,reumatismo).
hierba_para(tabaco,reumatismo).
hierba_para(cabellos_elote,riñones).
hierba_para(cola_cebolla,riñones).
hierba_para(apio,riñones).
hierba_para(eucalipto,ronquera).
hierba_para(pino,ronquera).
hierba_para(gordolobo,ronquera).
hierba_para(ajo,sabañones).
hierba_para(cebolla,sabañones).
hierba_para(estafiate,san_vito).
hierba_para(valeriana,san_vito).
hierba_para(borraja,sarampion).
hierba_para(ortiga,sarampion).
hierba_para(sauco,sarampion).
hierba_para(ajo,sarna).
hierba_para(alcanfor,sarna).
hierba_para(menta,sarna).
hierba_para(tomillo,sarna).
hierba_para(romero,sarna).
hierba_para(encina,salpullido).
hierba_para(salvia,salpullido).
hierba_para(tila,salpullido).
hierba_para(limon,sed).
hierba_para(tamarindo,sed).
hierba_para(pirul,sed).
hierba_para(semilla_calabaza,solitaria).
hierba_para(granada,solitaria).
hierba_para(coquito_aceite,solitaria).
hierba_para(raiz_granada_agria,solitaria).
hierba_para(helecho_macho,solitaria).
hierba_para(encina,sudoracion_excesiva).
hierba_para(alcanfor,tifoidea).
hierba_para(borraja,tifoidea).
hierba_para(quina,tifoidea).
hierba_para(canela,tifoidea).
hierba_para(romero,tifoidea).
hierba_para(salvia,tifoidea).
hierba_para(berro,tiña).
hierba_para(tila,tiña).
hierba_para(tamarindo,tiña).
hierba_para(salvia,tiña).
hierba_para(eucalipto,tos).
hierba_para(capulin,tos).
hierba_para(cedron,tos).
hierba_para(salvia,tos).
hierba_para(malva,tos).
hierba_para(marrubio,tos).
hierba_para(gelsemio,tos_ferina).
hierba_para(quina,tos_ferina).
hierba_para(rabano,tos_ferina).
hierba_para(violeta,tos_ferina).
hierba_para(jugo_vastago_platano_morado,tuberculosis).
hierba_para(mastuerzo,tuberculosis).
hierba_para(berro,tuberculosis).
hierba_para(ajo,tuberculosis).
hierba_para(eucalipto,tuberculosis).
hierba_para(pirul,tuberculosis).
hierba_para(pino,tuberculosis).
hierba_para(roble,tuberculosis).
hierba_para(cuachalalate,ulcera).
hierba_para(sanguinaria,ulcera).
hierba_para(cola_caballo,ulcera).
hierba_para(girasol,ulcera).
hierba_para(limon,urticaria).
hierba_para(ruibardo,urticaria).
hierba_para(hamamelis,varices).
hierba_para(castaño_indias,varices).
hierba_para(llanten,varices).
hierba_para(toronjil,varices).
hierba_para(apio,vejiga).
hierba_para(cipres,vejiga).
hierba_para(cola_caballo,vejiga).
hierba_para(ortiga,vejiga).
hierba_para(malva,vejiga).
hierba_para(leche_higuera,verrugas).
hierba_para(cebolla,verrugas).
hierba_para(nogal,verrugas).
hierba_para(albahaca,vertigo).
hierba_para(espino,vertigo).
hierba_para(menta,vomitos).
hierba_para(tila,vomitos).
hierba_para(marrubio,vomitos).
hierba_para(valeriana,vomitos).
hierba_para(salvia,vomitos).
hierba_para(cilantro,voz).
hierba_para(ajo,voz).
hierba_para(limon,voz).
hierba_para(pino,voz).
hierba_para(alfalfa,faltas_vitaminas).
hierba_para(espinacas,faltas_vitaminas).
hierba_para(acelga,faltas_vitaminas).
hierba_para(berro,faltas_vitaminas).
hierba_para(cebolla,faltas_vitaminas).
hierba_para(limon,faltas_vitaminas).
hierba_para(zanahoria,faltas_vitaminas).
hierba_para(aceite_bacalao,faltas_vitaminas).

%Pasos del 5-7 de la asignacion
hierba_para(diente_leon,depurar_sangre).
hierba_para(diente_leon,limpiar_sangre).
hierba_para(diente_leon,purificar_higado).
hierba_para(diente_leon,purificar_riñones).
hierba_para(diente_leon,limpiar_urea_sangre).
hierba_para(diente_leon,anemia).
hierba_para(diente_leon,debilidad).
hierba_para(diente_leon,laxante).
hierba_para(digitaria,miocarditis).
hierba_para(digitaria,astenia).
hierba_para(digitaria,asistolia).
hierba_para(digitaria,epilepsia).
hierba_para(doradilla,calculos_biliares).
hierba_para(digitaria,afecciones_riñones).
hierba_para(digitaria,afecciones_vejiga).
hierba_para(digitaria,congestion).
hierba_para(digitaria,irritacion_higado).